project:
  type: website
  output-dir: docs

website:
  title: "Expanding the Epi Training Kit"
  navbar:
    logo: logo_white.svg
    tools:
      - icon: github
        menu:
          - text: CÃ³digo fuente
            url:  https://epiverse-trace.github.io/translation-epitkit/
          - text: Reportar un error
            url:  https://github.com/epiverse-trace/translation-epitkit/issues
  repo-url: https://github.com/epiverse-trace/translation-epitkit/
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, epiversetheme.scss]
    css: styles.css
    toc: true

